/**
 * Merge cart/checkout/legal chrome + legal metadata into locale overlays.
 * Run: npx tsx scripts/merge-launch-ui.ts
 */
import { readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';

import type { LocalizedLocale } from '../lib/i18n/config';
import { LOCALIZED_LOCALES } from '../lib/i18n/config';
import type { UiDictionary } from '../lib/i18n/content/ui-english';

type ExtraUi = Pick<UiDictionary, 'cart' | 'checkout' | 'orderSuccess' | 'trackOrder' | 'legalChrome'>;

const extras: Record<LocalizedLocale, ExtraUi> = {
  es: {
    cart: {
      title: 'Carrito',
      yourCart: 'Tu carrito',
      loading: 'Cargando el carrito…',
      ariaLabel: 'Carrito de compra',
      reviewIntro: 'Revisa los detalles del paquete y continúa al pago seguro.',
      drawerDescription: 'Revisa tus paquetes y continúa al pago seguro.',
      emptyTitle: 'Tu carrito está vacío',
      emptyBody: 'Explora nuestros servicios de crecimiento y añade un paquete cuando quieras.',
      browseServices: 'Ver servicios',
      continueShopping: 'Seguir comprando',
      continueToCheckout: 'Ir al pago',
      checkout: 'Pagar',
      viewFullCart: 'Ver carrito completo',
      orderSummary: 'Resumen del pedido',
      quantity: 'Cantidad',
      price: 'Precio',
      subtotal: 'Subtotal',
      discount: 'Descuento',
      total: 'Total',
      remove: 'Quitar',
      edit: 'Editar',
      delivery: 'Entrega',
      couponCode: 'Código de cupón',
      couponPlaceholder: 'Introduce el código',
      apply: 'Aplicar',
      couponApplied: 'aplicado.',
      coupon: 'Cupón',
      removeCoupon: 'Quitar cupón',
      couponAppliedShort: 'Cupón aplicado.',
      goingToCheckout: 'Yendo al pago…',
      continuing: 'Continuando…',
      unableToContinue: 'No se pudo continuar al pago.',
      checkoutTimeout: 'El pago está tardando demasiado. Inténtalo de nuevo.',
    },
    checkout: {
      title: 'Pago',
      loading: 'Cargando el pago…',
      ariaLabel: 'Pago',
      intro: 'Confirma tus datos y completa el pago de forma segura.',
      emptyCart: 'Tu carrito está vacío.',
      returnToCart: 'Volver al carrito',
      customerInformation: 'Información del cliente',
      email: 'Correo electrónico',
      firstName: 'Nombre',
      lastName: 'Apellidos',
      marketingOptIn: 'Enviarme ofertas y descuentos',
      marketingHint:
        'Opcional. Puedes darte de baja cuando quieras. Solo enviamos correos de marketing si lo aceptas.',
      payment: 'Pago',
      paymentMethod: 'Método de pago',
      secureCardPayment: 'Pago con tarjeta seguro.',
      cardProcessedSecurely: 'Los pagos con tarjeta se procesan de forma segura',
      encryptedPayment: 'Pago cifrado · nunca almacenamos el número completo de la tarjeta',
      secureCheckout: 'Pago seguro',
      noPassword: 'Sin contraseña · solo perfil público',
      placeOrder: 'Hacer pedido',
      placingOrder: 'Procesando el pedido…',
      processing: 'Procesando',
      back: 'Atrás',
      required: 'Obligatorio',
      validEmail: 'Introduce un correo electrónico válido.',
      selectPayment: 'Selecciona un método de pago.',
      acceptTerms: 'Acepta los términos para continuar.',
      unableToPlace: 'No se pudo hacer el pedido.',
      unableToPlaceRetry: 'No se pudo hacer el pedido. Inténtalo de nuevo.',
      paymentError: 'Error de pago',
      orderError: 'Error del pedido',
      paymentCancelled:
        'El pago se canceló. Tu carrito sigue disponible: puedes intentar el pago de nuevo cuando quieras.',
      termsAgreePrefix: 'Acepto los',
      termsOfService: 'Términos del servicio',
      privacyPolicy: 'Política de privacidad',
      refundPolicy: 'Política de reembolso',
      termsJoin: ', ',
      termsAnd: ' y la ',
      termsPeriod: '.',
      secureGuarantee: 'Pago seguro · Garantía de reembolso de 30 días',
      stepPackage: 'Elegir paquete',
      stepDetails: 'Introducir datos',
      stepReview: 'Revisar',
      stepPayment: 'Pago',
      progressAria: 'Progreso del pago',
    },
    orderSuccess: {
      paymentConfirmed: 'Pago confirmado',
      confirmingPayment: 'Confirmando el pago',
      orderStatus: 'Estado del pedido',
      verifiedBody:
        'Gracias: tu pago se verificó y tu pedido está en la cola de entrega.',
      pendingBody:
        'Estamos confirmando tu pago. Esta página mostrará el éxito cuando Stripe verifique el cargo.',
      unverifiedBody:
        'Aún no pudimos verificar este pedido. Usa tu ID de pedido y tu correo para consultar el estado.',
      orderId: 'ID del pedido:',
      email: 'Correo:',
      trackOrder: 'Seguir pedido',
      backHome: 'Volver al inicio',
      ariaLabel: 'Pedido realizado',
    },
    trackOrder: {
      title: 'Sigue tu pedido',
      intro: 'Introduce tu ID de pedido y el correo usado en el pago. No hace falta una cuenta.',
      stepId: 'Introduce tu ID de pedido',
      stepEmail: 'Confirma el correo del pago',
      stepStatus: 'Consulta las actualizaciones de estado',
      orderId: 'ID del pedido',
      email: 'Correo electrónico',
      submit: 'Seguir pedido',
      progress: 'Progreso',
      ariaLabel: 'Seguimiento del pedido',
      serverError: 'Algo salió mal. Inténtalo de nuevo en un momento.',
    },
    legalChrome: {
      effectiveDate: 'Fecha de entrada en vigor:',
      lastUpdated: 'Última actualización:',
      datesPending:
        'Las fechas de entrada en vigor y de última actualización aparecerán aquí cuando estén configuradas para su publicación.',
      questionsTitle: '¿Tienes preguntas sobre esta política?',
      questionsBody:
        'Contacta con el soporte de NovaLikes a través de la página de [Contacto](/contact). Si tu consulta se refiere a un pedido existente, incluye tu referencia de pedido y el correo usado en el pago.',
      contactSupport: 'Contactar con soporte',
      contactAria: 'Contactar con soporte',
    },
  },
  de: {
    cart: {
      title: 'Warenkorb',
      yourCart: 'Ihr Warenkorb',
      loading: 'Warenkorb wird geladen…',
      ariaLabel: 'Warenkorb',
      reviewIntro: 'Prüfen Sie Ihre Paketdetails und fahren Sie zur sicheren Zahlung fort.',
      drawerDescription: 'Prüfen Sie Ihre Pakete und fahren Sie zur sicheren Zahlung fort.',
      emptyTitle: 'Ihr Warenkorb ist leer',
      emptyBody: 'Durchstöbern Sie unsere Wachstumsservices und fügen Sie ein Paket hinzu, wenn Sie bereit sind.',
      browseServices: 'Services ansehen',
      continueShopping: 'Weiter einkaufen',
      continueToCheckout: 'Zur Kasse',
      checkout: 'Kasse',
      viewFullCart: 'Warenkorb öffnen',
      orderSummary: 'Bestellübersicht',
      quantity: 'Menge',
      price: 'Preis',
      subtotal: 'Zwischensumme',
      discount: 'Rabatt',
      total: 'Gesamt',
      remove: 'Entfernen',
      edit: 'Bearbeiten',
      delivery: 'Lieferung',
      couponCode: 'Gutscheincode',
      couponPlaceholder: 'Code eingeben',
      apply: 'Anwenden',
      couponApplied: 'angewendet.',
      coupon: 'Gutschein',
      removeCoupon: 'Gutschein entfernen',
      couponAppliedShort: 'Gutschein angewendet.',
      goingToCheckout: 'Weiter zur Kasse…',
      continuing: 'Wird fortgesetzt…',
      unableToContinue: 'Weiter zur Kasse nicht möglich.',
      checkoutTimeout: 'Die Kasse dauert zu lange. Bitte versuchen Sie es erneut.',
    },
    checkout: {
      title: 'Kasse',
      loading: 'Kasse wird geladen…',
      ariaLabel: 'Kasse',
      intro: 'Bestätigen Sie Ihre Angaben und schließen Sie die Zahlung sicher ab.',
      emptyCart: 'Ihr Warenkorb ist leer.',
      returnToCart: 'Zurück zum Warenkorb',
      customerInformation: 'Kundeninformationen',
      email: 'E-Mail-Adresse',
      firstName: 'Vorname',
      lastName: 'Nachname',
      marketingOptIn: 'Angebote und Rabatte per E-Mail erhalten',
      marketingHint:
        'Optional. Sie können sich jederzeit abmelden. Marketing-E-Mails senden wir nur mit Ihrer Einwilligung.',
      payment: 'Zahlung',
      paymentMethod: 'Zahlungsmethode',
      secureCardPayment: 'Sichere Kartenzahlung.',
      cardProcessedSecurely: 'Kartenzahlungen werden sicher verarbeitet',
      encryptedPayment: 'Verschlüsselte Zahlung · wir speichern niemals vollständige Kartennummern',
      secureCheckout: 'Sichere Kasse',
      noPassword: 'Kein Passwort erforderlich · nur öffentliches Profil',
      placeOrder: 'Bestellung aufgeben',
      placingOrder: 'Bestellung wird aufgegeben…',
      processing: 'Wird verarbeitet',
      back: 'Zurück',
      required: 'Erforderlich',
      validEmail: 'Geben Sie eine gültige E-Mail-Adresse ein.',
      selectPayment: 'Wählen Sie eine Zahlungsmethode.',
      acceptTerms: 'Bitte akzeptieren Sie die Bedingungen, um fortzufahren.',
      unableToPlace: 'Bestellung konnte nicht aufgegeben werden.',
      unableToPlaceRetry: 'Bestellung konnte nicht aufgegeben werden. Bitte versuchen Sie es erneut.',
      paymentError: 'Zahlungsfehler',
      orderError: 'Bestellfehler',
      paymentCancelled:
        'Die Zahlung wurde abgebrochen. Ihr Warenkorb ist weiterhin verfügbar — Sie können die Kasse erneut versuchen, wenn Sie bereit sind.',
      termsAgreePrefix: 'Ich stimme den',
      termsOfService: 'Nutzungsbedingungen',
      privacyPolicy: 'Datenschutzrichtlinie',
      refundPolicy: 'Rückerstattungsrichtlinie',
      termsJoin: ', der ',
      termsAnd: ' und der ',
      termsPeriod: ' zu.',
      secureGuarantee: 'Sichere Kasse · 30-Tage-Geld-zurück-Garantie',
      stepPackage: 'Paket wählen',
      stepDetails: 'Daten eingeben',
      stepReview: 'Prüfen',
      stepPayment: 'Zahlung',
      progressAria: 'Kassenschritte',
    },
    orderSuccess: {
      paymentConfirmed: 'Zahlung bestätigt',
      confirmingPayment: 'Zahlung wird bestätigt',
      orderStatus: 'Bestellstatus',
      verifiedBody:
        'Danke — Ihre Zahlung wurde bestätigt und Ihre Bestellung befindet sich in der Erfüllungswarteschlange.',
      pendingBody:
        'Wir bestätigen Ihre Zahlung. Diese Seite zeigt den Erfolg, sobald Stripe die Belastung bestätigt.',
      unverifiedBody:
        'Wir konnten diese Bestellung noch nicht bestätigen. Nutzen Sie Ihre Bestell-ID und E-Mail, um den Status zu prüfen.',
      orderId: 'Bestell-ID:',
      email: 'E-Mail:',
      trackOrder: 'Bestellung verfolgen',
      backHome: 'Zur Startseite',
      ariaLabel: 'Bestellung erfolgreich',
    },
    trackOrder: {
      title: 'Bestellung verfolgen',
      intro: 'Geben Sie Ihre Bestell-ID und die E-Mail aus der Kasse ein. Kein Konto erforderlich.',
      stepId: 'Bestell-ID eingeben',
      stepEmail: 'Kassen-E-Mail bestätigen',
      stepStatus: 'Statusaktualisierungen ansehen',
      orderId: 'Bestell-ID',
      email: 'E-Mail-Adresse',
      submit: 'Bestellung verfolgen',
      progress: 'Fortschritt',
      ariaLabel: 'Bestellung verfolgen',
      serverError: 'Etwas ist schiefgelaufen. Bitte versuchen Sie es in einem Moment erneut.',
    },
    legalChrome: {
      effectiveDate: 'Gültig ab:',
      lastUpdated: 'Zuletzt aktualisiert:',
      datesPending:
        'Das Gültigkeitsdatum und das Datum der letzten Aktualisierung erscheinen hier, sobald sie für die Veröffentlichung hinterlegt sind.',
      questionsTitle: 'Fragen zu dieser Richtlinie?',
      questionsBody:
        'Kontaktieren Sie den NovaLikes-Support über die Seite [Kontakt](/contact). Wenn sich Ihre Frage auf eine bestehende Bestellung bezieht, geben Sie bitte Ihre Bestellreferenz und die bei der Kasse verwendete E-Mail an.',
      contactSupport: 'Support kontaktieren',
      contactAria: 'Support kontaktieren',
    },
  },
  fr: {
    cart: {
      title: 'Panier',
      yourCart: 'Votre panier',
      loading: 'Chargement du panier…',
      ariaLabel: 'Panier',
      reviewIntro: 'Vérifiez les détails de votre forfait, puis continuez vers le paiement sécurisé.',
      drawerDescription: 'Vérifiez vos forfaits, puis continuez vers le paiement sécurisé.',
      emptyTitle: 'Votre panier est vide',
      emptyBody: 'Parcourez nos services de croissance et ajoutez un forfait quand vous êtes prêt.',
      browseServices: 'Voir les services',
      continueShopping: 'Continuer vos achats',
      continueToCheckout: 'Passer au paiement',
      checkout: 'Paiement',
      viewFullCart: 'Voir le panier complet',
      orderSummary: 'Récapitulatif de commande',
      quantity: 'Quantité',
      price: 'Prix',
      subtotal: 'Sous-total',
      discount: 'Remise',
      total: 'Total',
      remove: 'Retirer',
      edit: 'Modifier',
      delivery: 'Livraison',
      couponCode: 'Code promo',
      couponPlaceholder: 'Saisir le code',
      apply: 'Appliquer',
      couponApplied: 'appliqué.',
      coupon: 'Code promo',
      removeCoupon: 'Retirer le code promo',
      couponAppliedShort: 'Code promo appliqué.',
      goingToCheckout: 'Redirection vers le paiement…',
      continuing: 'Poursuite…',
      unableToContinue: 'Impossible de continuer vers le paiement.',
      checkoutTimeout: 'Le paiement met trop de temps. Veuillez réessayer.',
    },
    checkout: {
      title: 'Paiement',
      loading: 'Chargement du paiement…',
      ariaLabel: 'Paiement',
      intro: 'Confirmez vos informations et finalisez le paiement en toute sécurité.',
      emptyCart: 'Votre panier est vide.',
      returnToCart: 'Retour au panier',
      customerInformation: 'Informations client',
      email: 'Adresse e-mail',
      firstName: 'Prénom',
      lastName: 'Nom',
      marketingOptIn: 'M’envoyer des offres et des réductions',
      marketingHint:
        'Facultatif. Vous pouvez vous désabonner à tout moment. Nous n’envoyons d’e-mails marketing que si vous y consentez.',
      payment: 'Paiement',
      paymentMethod: 'Moyen de paiement',
      secureCardPayment: 'Paiement par carte sécurisé.',
      cardProcessedSecurely: 'Les paiements par carte sont traités de manière sécurisée',
      encryptedPayment: 'Paiement chiffré · nous ne stockons jamais le numéro complet de la carte',
      secureCheckout: 'Paiement sécurisé',
      noPassword: 'Aucun mot de passe requis · profil public uniquement',
      placeOrder: 'Passer la commande',
      placingOrder: 'Commande en cours…',
      processing: 'Traitement',
      back: 'Retour',
      required: 'Obligatoire',
      validEmail: 'Saisissez une adresse e-mail valide.',
      selectPayment: 'Sélectionnez un moyen de paiement.',
      acceptTerms: 'Veuillez accepter les conditions pour continuer.',
      unableToPlace: 'Impossible de passer la commande.',
      unableToPlaceRetry: 'Impossible de passer la commande. Veuillez réessayer.',
      paymentError: 'Erreur de paiement',
      orderError: 'Erreur de commande',
      paymentCancelled:
        'Le paiement a été annulé. Votre panier est toujours disponible — vous pouvez réessayer le paiement quand vous le souhaitez.',
      termsAgreePrefix: 'J’accepte les',
      termsOfService: 'Conditions d’utilisation',
      privacyPolicy: 'Politique de confidentialité',
      refundPolicy: 'Politique de remboursement',
      termsJoin: ', la ',
      termsAnd: ' et la ',
      termsPeriod: '.',
      secureGuarantee: 'Paiement sécurisé · Garantie de remboursement de 30 jours',
      stepPackage: 'Choisir le forfait',
      stepDetails: 'Saisir les informations',
      stepReview: 'Vérifier',
      stepPayment: 'Paiement',
      progressAria: 'Progression du paiement',
    },
    orderSuccess: {
      paymentConfirmed: 'Paiement confirmé',
      confirmingPayment: 'Confirmation du paiement',
      orderStatus: 'Statut de la commande',
      verifiedBody:
        'Merci — votre paiement a été vérifié et votre commande est dans la file de traitement.',
      pendingBody:
        'Nous confirmons votre paiement. Cette page affichera le succès une fois que Stripe aura vérifié le débit.',
      unverifiedBody:
        'Nous n’avons pas encore pu vérifier cette commande. Utilisez votre identifiant de commande et votre e-mail pour suivre le statut.',
      orderId: 'Identifiant de commande :',
      email: 'E-mail :',
      trackOrder: 'Suivre la commande',
      backHome: 'Retour à l’accueil',
      ariaLabel: 'Commande confirmée',
    },
    trackOrder: {
      title: 'Suivre votre commande',
      intro: 'Saisissez votre identifiant de commande et l’e-mail utilisé au paiement. Aucun compte n’est requis.',
      stepId: 'Saisissez votre identifiant de commande',
      stepEmail: 'Confirmez l’e-mail du paiement',
      stepStatus: 'Consultez les mises à jour de statut',
      orderId: 'Identifiant de commande',
      email: 'Adresse e-mail',
      submit: 'Suivre la commande',
      progress: 'Progression',
      ariaLabel: 'Suivi de commande',
      serverError: 'Un problème est survenu. Veuillez réessayer dans un instant.',
    },
    legalChrome: {
      effectiveDate: 'Date d’entrée en vigueur :',
      lastUpdated: 'Dernière mise à jour :',
      datesPending:
        'Les dates d’entrée en vigueur et de dernière mise à jour apparaîtront ici une fois configurées pour publication.',
      questionsTitle: 'Des questions sur cette politique ?',
      questionsBody:
        'Contactez le support NovaLikes via la page [Contact](/contact). Si votre question concerne une commande existante, indiquez votre référence de commande et l’e-mail utilisé au paiement.',
      contactSupport: 'Contacter le support',
      contactAria: 'Contacter le support',
    },
  },
  it: {
    cart: {
      title: 'Carrello',
      yourCart: 'Il tuo carrello',
      loading: 'Caricamento del carrello…',
      ariaLabel: 'Carrello',
      reviewIntro: 'Controlla i dettagli del pacchetto e continua al pagamento sicuro.',
      drawerDescription: 'Controlla i pacchetti e continua al pagamento sicuro.',
      emptyTitle: 'Il tuo carrello è vuoto',
      emptyBody: 'Sfoglia i nostri servizi di crescita e aggiungi un pacchetto quando sei pronto.',
      browseServices: 'Vedi i servizi',
      continueShopping: 'Continua gli acquisti',
      continueToCheckout: 'Vai al pagamento',
      checkout: 'Pagamento',
      viewFullCart: 'Vedi il carrello completo',
      orderSummary: 'Riepilogo ordine',
      quantity: 'Quantità',
      price: 'Prezzo',
      subtotal: 'Subtotale',
      discount: 'Sconto',
      total: 'Totale',
      remove: 'Rimuovi',
      edit: 'Modifica',
      delivery: 'Consegna',
      couponCode: 'Codice coupon',
      couponPlaceholder: 'Inserisci il codice',
      apply: 'Applica',
      couponApplied: 'applicato.',
      coupon: 'Coupon',
      removeCoupon: 'Rimuovi coupon',
      couponAppliedShort: 'Coupon applicato.',
      goingToCheckout: 'Passaggio al pagamento…',
      continuing: 'Continuazione…',
      unableToContinue: 'Impossibile continuare al pagamento.',
      checkoutTimeout: 'Il pagamento sta impiegando troppo tempo. Riprova.',
    },
    checkout: {
      title: 'Pagamento',
      loading: 'Caricamento del pagamento…',
      ariaLabel: 'Pagamento',
      intro: 'Conferma i tuoi dati e completa il pagamento in modo sicuro.',
      emptyCart: 'Il tuo carrello è vuoto.',
      returnToCart: 'Torna al carrello',
      customerInformation: 'Informazioni cliente',
      email: 'Indirizzo e-mail',
      firstName: 'Nome',
      lastName: 'Cognome',
      marketingOptIn: 'Inviami offerte e sconti',
      marketingHint:
        'Facoltativo. Puoi annullare l’iscrizione in qualsiasi momento. Inviamo e-mail di marketing solo se acconsenti.',
      payment: 'Pagamento',
      paymentMethod: 'Metodo di pagamento',
      secureCardPayment: 'Pagamento con carta sicuro.',
      cardProcessedSecurely: 'I pagamenti con carta vengono elaborati in modo sicuro',
      encryptedPayment: 'Pagamento crittografato · non memorizziamo mai il numero completo della carta',
      secureCheckout: 'Pagamento sicuro',
      noPassword: 'Nessuna password richiesta · solo profilo pubblico',
      placeOrder: 'Invia ordine',
      placingOrder: 'Invio dell’ordine…',
      processing: 'Elaborazione',
      back: 'Indietro',
      required: 'Obbligatorio',
      validEmail: 'Inserisci un indirizzo e-mail valido.',
      selectPayment: 'Seleziona un metodo di pagamento.',
      acceptTerms: 'Accetta i termini per continuare.',
      unableToPlace: 'Impossibile inviare l’ordine.',
      unableToPlaceRetry: 'Impossibile inviare l’ordine. Riprova.',
      paymentError: 'Errore di pagamento',
      orderError: 'Errore dell’ordine',
      paymentCancelled:
        'Il pagamento è stato annullato. Il carrello è ancora disponibile: puoi riprovare il pagamento quando vuoi.',
      termsAgreePrefix: 'Accetto i',
      termsOfService: 'Termini di servizio',
      privacyPolicy: 'Informativa sulla privacy',
      refundPolicy: 'Politica di rimborso',
      termsJoin: ', l’',
      termsAnd: ' e la ',
      termsPeriod: '.',
      secureGuarantee: 'Pagamento sicuro · Garanzia di rimborso di 30 giorni',
      stepPackage: 'Scegli il pacchetto',
      stepDetails: 'Inserisci i dati',
      stepReview: 'Rivedi',
      stepPayment: 'Pagamento',
      progressAria: 'Avanzamento del pagamento',
    },
    orderSuccess: {
      paymentConfirmed: 'Pagamento confermato',
      confirmingPayment: 'Conferma del pagamento',
      orderStatus: 'Stato dell’ordine',
      verifiedBody:
        'Grazie: il pagamento è stato verificato e l’ordine è in coda di evasione.',
      pendingBody:
        'Stiamo confermando il pagamento. Questa pagina mostrerà il successo quando Stripe verificherà l’addebito.',
      unverifiedBody:
        'Non abbiamo ancora potuto verificare questo ordine. Usa l’ID ordine e l’e-mail per controllare lo stato.',
      orderId: 'ID ordine:',
      email: 'E-mail:',
      trackOrder: 'Traccia ordine',
      backHome: 'Torna alla home',
      ariaLabel: 'Ordine confermato',
    },
    trackOrder: {
      title: 'Traccia il tuo ordine',
      intro: 'Inserisci l’ID ordine e l’e-mail usata al pagamento. Non è richiesto un account.',
      stepId: 'Inserisci l’ID ordine',
      stepEmail: 'Conferma l’e-mail del pagamento',
      stepStatus: 'Vedi gli aggiornamenti di stato',
      orderId: 'ID ordine',
      email: 'Indirizzo e-mail',
      submit: 'Traccia ordine',
      progress: 'Avanzamento',
      ariaLabel: 'Tracciamento ordine',
      serverError: 'Qualcosa è andato storto. Riprova tra un momento.',
    },
    legalChrome: {
      effectiveDate: 'Data di entrata in vigore:',
      lastUpdated: 'Ultimo aggiornamento:',
      datesPending:
        'Le date di entrata in vigore e di ultimo aggiornamento appariranno qui quando saranno configurate per la pubblicazione.',
      questionsTitle: 'Domande su questa informativa?',
      questionsBody:
        'Contatta il supporto NovaLikes tramite la pagina [Contatti](/contact). Se la domanda riguarda un ordine esistente, includi il riferimento dell’ordine e l’e-mail usata al pagamento.',
      contactSupport: 'Contatta il supporto',
      contactAria: 'Contatta il supporto',
    },
  },
  'pt-br': {
    cart: {
      title: 'Carrinho',
      yourCart: 'Seu carrinho',
      loading: 'Carregando o carrinho…',
      ariaLabel: 'Carrinho de compras',
      reviewIntro: 'Revise os detalhes do pacote e continue para o pagamento seguro.',
      drawerDescription: 'Revise seus pacotes e continue para o pagamento seguro.',
      emptyTitle: 'Seu carrinho está vazio',
      emptyBody: 'Explore nossos serviços de crescimento e adicione um pacote quando quiser.',
      browseServices: 'Ver serviços',
      continueShopping: 'Continuar comprando',
      continueToCheckout: 'Ir para o pagamento',
      checkout: 'Pagamento',
      viewFullCart: 'Ver carrinho completo',
      orderSummary: 'Resumo do pedido',
      quantity: 'Quantidade',
      price: 'Preço',
      subtotal: 'Subtotal',
      discount: 'Desconto',
      total: 'Total',
      remove: 'Remover',
      edit: 'Editar',
      delivery: 'Entrega',
      couponCode: 'Código de cupom',
      couponPlaceholder: 'Digite o código',
      apply: 'Aplicar',
      couponApplied: 'aplicado.',
      coupon: 'Cupom',
      removeCoupon: 'Remover cupom',
      couponAppliedShort: 'Cupom aplicado.',
      goingToCheckout: 'Indo para o pagamento…',
      continuing: 'Continuando…',
      unableToContinue: 'Não foi possível continuar para o pagamento.',
      checkoutTimeout: 'O pagamento está demorando demais. Tente novamente.',
    },
    checkout: {
      title: 'Pagamento',
      loading: 'Carregando o pagamento…',
      ariaLabel: 'Pagamento',
      intro: 'Confirme seus dados e conclua o pagamento com segurança.',
      emptyCart: 'Seu carrinho está vazio.',
      returnToCart: 'Voltar ao carrinho',
      customerInformation: 'Informações do cliente',
      email: 'E-mail',
      firstName: 'Nome',
      lastName: 'Sobrenome',
      marketingOptIn: 'Enviar ofertas e descontos por e-mail',
      marketingHint:
        'Opcional. Você pode cancelar a qualquer momento. Só enviamos e-mails de marketing se você autorizar.',
      payment: 'Pagamento',
      paymentMethod: 'Forma de pagamento',
      secureCardPayment: 'Pagamento com cartão seguro.',
      cardProcessedSecurely: 'Os pagamentos com cartão são processados com segurança',
      encryptedPayment: 'Pagamento criptografado · nunca armazenamos o número completo do cartão',
      secureCheckout: 'Pagamento seguro',
      noPassword: 'Sem senha · apenas perfil público',
      placeOrder: 'Fazer pedido',
      placingOrder: 'Enviando o pedido…',
      processing: 'Processando',
      back: 'Voltar',
      required: 'Obrigatório',
      validEmail: 'Informe um e-mail válido.',
      selectPayment: 'Selecione uma forma de pagamento.',
      acceptTerms: 'Aceite os termos para continuar.',
      unableToPlace: 'Não foi possível fazer o pedido.',
      unableToPlaceRetry: 'Não foi possível fazer o pedido. Tente novamente.',
      paymentError: 'Erro de pagamento',
      orderError: 'Erro do pedido',
      paymentCancelled:
        'O pagamento foi cancelado. Seu carrinho ainda está disponível — você pode tentar o pagamento de novo quando quiser.',
      termsAgreePrefix: 'Concordo com os',
      termsOfService: 'Termos de serviço',
      privacyPolicy: 'Política de privacidade',
      refundPolicy: 'Política de reembolso',
      termsJoin: ', a ',
      termsAnd: ' e a ',
      termsPeriod: '.',
      secureGuarantee: 'Pagamento seguro · Garantia de reembolso de 30 dias',
      stepPackage: 'Escolher pacote',
      stepDetails: 'Inserir dados',
      stepReview: 'Revisar',
      stepPayment: 'Pagamento',
      progressAria: 'Progresso do pagamento',
    },
    orderSuccess: {
      paymentConfirmed: 'Pagamento confirmado',
      confirmingPayment: 'Confirmando o pagamento',
      orderStatus: 'Status do pedido',
      verifiedBody:
        'Obrigado — seu pagamento foi verificado e o pedido está na fila de cumprimento.',
      pendingBody:
        'Estamos confirmando seu pagamento. Esta página mostrará o sucesso quando o Stripe verificar a cobrança.',
      unverifiedBody:
        'Ainda não foi possível verificar este pedido. Use o ID do pedido e o e-mail para acompanhar o status.',
      orderId: 'ID do pedido:',
      email: 'E-mail:',
      trackOrder: 'Acompanhar pedido',
      backHome: 'Voltar ao início',
      ariaLabel: 'Pedido confirmado',
    },
    trackOrder: {
      title: 'Acompanhe seu pedido',
      intro: 'Informe o ID do pedido e o e-mail usado no pagamento. Não é necessária uma conta.',
      stepId: 'Informe o ID do pedido',
      stepEmail: 'Confirme o e-mail do pagamento',
      stepStatus: 'Veja as atualizações de status',
      orderId: 'ID do pedido',
      email: 'E-mail',
      submit: 'Acompanhar pedido',
      progress: 'Progresso',
      ariaLabel: 'Acompanhamento do pedido',
      serverError: 'Algo deu errado. Tente novamente em instantes.',
    },
    legalChrome: {
      effectiveDate: 'Data de vigência:',
      lastUpdated: 'Última atualização:',
      datesPending:
        'As datas de vigência e de última atualização aparecerão aqui quando forem configuradas para publicação.',
      questionsTitle: 'Dúvidas sobre esta política?',
      questionsBody:
        'Fale com o suporte da NovaLikes pela página de [Contato](/contact). Se a dúvida for sobre um pedido existente, inclua a referência do pedido e o e-mail usado no pagamento.',
      contactSupport: 'Falar com o suporte',
      contactAria: 'Falar com o suporte',
    },
  },
  ar: {
    cart: {
      title: 'السلة',
      yourCart: 'سلتك',
      loading: 'جارٍ تحميل السلة…',
      ariaLabel: 'سلة التسوق',
      reviewIntro: 'راجع تفاصيل الباقة ثم تابع إلى الدفع الآمن.',
      drawerDescription: 'راجع باقاتك ثم تابع إلى الدفع الآمن.',
      emptyTitle: 'سلتك فارغة',
      emptyBody: 'تصفح خدمات النمو لدينا وأضف باقة عندما تكون جاهزًا.',
      browseServices: 'تصفح الخدمات',
      continueShopping: 'متابعة التسوق',
      continueToCheckout: 'المتابعة إلى الدفع',
      checkout: 'الدفع',
      viewFullCart: 'عرض السلة كاملة',
      orderSummary: 'ملخص الطلب',
      quantity: 'الكمية',
      price: 'السعر',
      subtotal: 'المجموع الفرعي',
      discount: 'الخصم',
      total: 'الإجمالي',
      remove: 'إزالة',
      edit: 'تعديل',
      delivery: 'التسليم',
      couponCode: 'رمز القسيمة',
      couponPlaceholder: 'أدخل الرمز',
      apply: 'تطبيق',
      couponApplied: 'مُطبَّق.',
      coupon: 'قسيمة',
      removeCoupon: 'إزالة القسيمة',
      couponAppliedShort: 'تم تطبيق القسيمة.',
      goingToCheckout: 'جارٍ الانتقال إلى الدفع…',
      continuing: 'جارٍ المتابعة…',
      unableToContinue: 'تعذر المتابعة إلى الدفع.',
      checkoutTimeout: 'يستغرق الدفع وقتًا أطول من المتوقع. حاول مرة أخرى.',
    },
    checkout: {
      title: 'الدفع',
      loading: 'جارٍ تحميل الدفع…',
      ariaLabel: 'الدفع',
      intro: 'أكد بياناتك وأكمل الدفع بأمان.',
      emptyCart: 'سلتك فارغة.',
      returnToCart: 'العودة إلى السلة',
      customerInformation: 'معلومات العميل',
      email: 'البريد الإلكتروني',
      firstName: 'الاسم الأول',
      lastName: 'اسم العائلة',
      marketingOptIn: 'أرسل لي العروض والخصومات',
      marketingHint:
        'اختياري. يمكنك إلغاء الاشتراك في أي وقت. نرسل رسائل تسويقية فقط إذا وافقت.',
      payment: 'الدفع',
      paymentMethod: 'طريقة الدفع',
      secureCardPayment: 'دفع آمن بالبطاقة.',
      cardProcessedSecurely: 'تُعالَج مدفوعات البطاقات بشكل آمن',
      encryptedPayment: 'دفع مشفّر · لا نخزّن أرقام البطاقات كاملة أبدًا',
      secureCheckout: 'دفع آمن',
      noPassword: 'لا كلمة مرور مطلوبة · ملف عام فقط',
      placeOrder: 'تأكيد الطلب',
      placingOrder: 'جارٍ تأكيد الطلب…',
      processing: 'جارٍ المعالجة',
      back: 'رجوع',
      required: 'مطلوب',
      validEmail: 'أدخل بريدًا إلكترونيًا صالحًا.',
      selectPayment: 'اختر طريقة دفع.',
      acceptTerms: 'يرجى قبول الشروط للمتابعة.',
      unableToPlace: 'تعذر تأكيد الطلب.',
      unableToPlaceRetry: 'تعذر تأكيد الطلب. حاول مرة أخرى.',
      paymentError: 'خطأ في الدفع',
      orderError: 'خطأ في الطلب',
      paymentCancelled:
        'أُلغي الدفع. سلتك ما زالت متاحة — يمكنك محاولة الدفع مرة أخرى عندما تكون جاهزًا.',
      termsAgreePrefix: 'أوافق على',
      termsOfService: 'شروط الخدمة',
      privacyPolicy: 'سياسة الخصوصية',
      refundPolicy: 'سياسة الاسترداد',
      termsJoin: ' و',
      termsAnd: ' و',
      termsPeriod: '.',
      secureGuarantee: 'دفع آمن · ضمان استرداد خلال 30 يومًا',
      stepPackage: 'اختيار الباقة',
      stepDetails: 'إدخال التفاصيل',
      stepReview: 'المراجعة',
      stepPayment: 'الدفع',
      progressAria: 'خطوات الدفع',
    },
    orderSuccess: {
      paymentConfirmed: 'تم تأكيد الدفع',
      confirmingPayment: 'جارٍ تأكيد الدفع',
      orderStatus: 'حالة الطلب',
      verifiedBody: 'شكرًا — تم التحقق من الدفع وأُضيف طلبك إلى قائمة التنفيذ.',
      pendingBody:
        'نؤكّد دفعتك. ستظهر هذه الصفحة حالة النجاح بعد أن يتحقق Stripe من العملية.',
      unverifiedBody:
        'تعذر التحقق من هذا الطلب بعد. استخدم معرّف الطلب والبريد الإلكتروني لتتبع الحالة.',
      orderId: 'معرّف الطلب:',
      email: 'البريد الإلكتروني:',
      trackOrder: 'تتبع الطلب',
      backHome: 'العودة إلى الرئيسية',
      ariaLabel: 'نجاح الطلب',
    },
    trackOrder: {
      title: 'تتبع طلبك',
      intro: 'أدخل معرّف الطلب والبريد الإلكتروني المستخدم عند الدفع. لا حاجة إلى حساب.',
      stepId: 'أدخل معرّف الطلب',
      stepEmail: 'أكد بريد الدفع الإلكتروني',
      stepStatus: 'اعرض تحديثات الحالة',
      orderId: 'معرّف الطلب',
      email: 'البريد الإلكتروني',
      submit: 'تتبع الطلب',
      progress: 'التقدم',
      ariaLabel: 'تتبع الطلب',
      serverError: 'حدث خطأ ما. حاول مرة أخرى بعد قليل.',
    },
    legalChrome: {
      effectiveDate: 'تاريخ السريان:',
      lastUpdated: 'آخر تحديث:',
      datesPending:
        'ستظهر هنا تواريخ السريان وآخر تحديث بعد إعدادها للنشر.',
      questionsTitle: 'أسئلة حول هذه السياسة؟',
      questionsBody:
        'تواصل مع دعم NovaLikes عبر صفحة [اتصل بنا](/contact). إذا كان سؤالك يتعلق بطلب قائم، أدرج مرجع الطلب والبريد الإلكتروني المستخدم عند الدفع.',
      contactSupport: 'تواصل مع الدعم',
      contactAria: 'تواصل مع الدعم',
    },
  },
};

const legalMeta: Record<
  LocalizedLocale,
  Record<
    'privacyPolicy' | 'refundPolicy' | 'termsAndConditions' | 'cookiePolicy' | 'disclaimer',
    { title: string; description: string }
  >
> = {
  es: {
    privacyPolicy: {
      title: 'Política de privacidad | NovaLikes',
      description:
        'Consulta cómo NovaLikes recopila, usa, almacena y trata la información cuando usas el sitio, los servicios de pago, las herramientas gratuitas y el soporte.',
    },
    refundPolicy: {
      title: 'Política de reembolso | Garantía de 30 días | NovaLikes',
      description:
        'Lee la garantía de reembolso de 30 días de NovaLikes, la elegibilidad, las exclusiones, las cancelaciones, las recargas y el proceso de solicitud.',
    },
    termsAndConditions: {
      title: 'Términos y condiciones | NovaLikes',
      description:
        'Lee los términos que rigen los servicios de NovaLikes, los pedidos, los pagos, las herramientas gratuitas, las responsabilidades del cliente, los reembolsos y el uso del sitio.',
    },
    cookiePolicy: {
      title: 'Política de cookies | NovaLikes',
      description:
        'Consulta cómo NovaLikes usa cookies y almacenamiento del navegador para el carrito, las sesiones de administración, las preferencias y otras funciones del sitio.',
    },
    disclaimer: {
      title: 'Aviso legal | NovaLikes',
      description:
        'Lee limitaciones importantes sobre los servicios de NovaLikes, las plataformas de terceros, las herramientas gratuitas, las métricas de redes sociales y el contenido descargado.',
    },
  },
  de: {
    privacyPolicy: {
      title: 'Datenschutz | NovaLikes',
      description:
        'Erfahren Sie, wie NovaLikes Informationen erhebt, verwendet, speichert und verarbeitet, wenn Sie die Website, bezahlte Dienste, kostenlose Tools und den Support nutzen.',
    },
    refundPolicy: {
      title: 'Rückerstattungsrichtlinie | 30-Tage-Geld-zurück-Garantie | NovaLikes',
      description:
        'Lesen Sie die 30-Tage-Geld-zurück-Garantie von NovaLikes, die Anspruchsvoraussetzungen, Ausschlüsse, Stornierungen, Nachlieferungen und den Antragsprozess.',
    },
    termsAndConditions: {
      title: 'Allgemeine Geschäftsbedingungen | NovaLikes',
      description:
        'Lesen Sie die Bedingungen für NovaLikes-Dienste, Bestellungen, Zahlungen, kostenlose Tools, Kundenpflichten, Rückerstattungen und die Nutzung der Website.',
    },
    cookiePolicy: {
      title: 'Cookie-Richtlinie | NovaLikes',
      description:
        'Erfahren Sie, wie NovaLikes Cookies und Browserspeicher für den Warenkorb, Admin-Sitzungen, Einstellungen und andere Website-Funktionen verwendet.',
    },
    disclaimer: {
      title: 'Haftungsausschluss | NovaLikes',
      description:
        'Lesen Sie wichtige Einschränkungen zu NovaLikes-Diensten, Drittplattformen, kostenlosen Tools, Social-Media-Kennzahlen und heruntergeladenen Inhalten.',
    },
  },
  fr: {
    privacyPolicy: {
      title: 'Politique de confidentialité | NovaLikes',
      description:
        'Découvrez comment NovaLikes collecte, utilise, stocke et traite les informations lorsque vous utilisez le site, les services payants, les outils gratuits et le support.',
    },
    refundPolicy: {
      title: 'Politique de remboursement | Garantie 30 jours | NovaLikes',
      description:
        'Lisez la garantie de remboursement de 30 jours NovaLikes, l’éligibilité, les exclusions, les annulations, les recharges et le processus de demande.',
    },
    termsAndConditions: {
      title: 'Conditions générales | NovaLikes',
      description:
        'Lisez les conditions qui régissent les services NovaLikes, les commandes, les paiements, les outils gratuits, les responsabilités du client, les remboursements et l’utilisation du site.',
    },
    cookiePolicy: {
      title: 'Politique de cookies | NovaLikes',
      description:
        'Découvrez comment NovaLikes utilise les cookies et le stockage du navigateur pour le panier, les sessions d’administration, les préférences et d’autres fonctions du site.',
    },
    disclaimer: {
      title: 'Mentions légales | NovaLikes',
      description:
        'Lisez d’importantes limitations concernant les services NovaLikes, les plateformes tierces, les outils gratuits, les indicateurs des réseaux sociaux et le contenu téléchargé.',
    },
  },
  it: {
    privacyPolicy: {
      title: 'Informativa sulla privacy | NovaLikes',
      description:
        'Scopri come NovaLikes raccoglie, usa, conserva e gestisce le informazioni quando usi il sito, i servizi a pagamento, gli strumenti gratuiti e il supporto.',
    },
    refundPolicy: {
      title: 'Politica di rimborso | Garanzia 30 giorni | NovaLikes',
      description:
        'Leggi la garanzia di rimborso di 30 giorni di NovaLikes, i requisiti, le esclusioni, le cancellazioni, i rifornimenti e la procedura di richiesta.',
    },
    termsAndConditions: {
      title: 'Termini e condizioni | NovaLikes',
      description:
        'Leggi i termini che regolano i servizi NovaLikes, gli ordini, i pagamenti, gli strumenti gratuiti, le responsabilità del cliente, i rimborsi e l’uso del sito.',
    },
    cookiePolicy: {
      title: 'Politica sui cookie | NovaLikes',
      description:
        'Scopri come NovaLikes usa cookie e archiviazione del browser per il carrello, le sessioni di amministrazione, le preferenze e altre funzioni del sito.',
    },
    disclaimer: {
      title: 'Esclusione di responsabilità | NovaLikes',
      description:
        'Leggi limitazioni importanti sui servizi NovaLikes, le piattaforme di terze parti, gli strumenti gratuiti, le metriche dei social e i contenuti scaricati.',
    },
  },
  'pt-br': {
    privacyPolicy: {
      title: 'Política de privacidade | NovaLikes',
      description:
        'Saiba como a NovaLikes coleta, usa, armazena e trata informações quando você usa o site, os serviços pagos, as ferramentas gratuitas e o suporte.',
    },
    refundPolicy: {
      title: 'Política de reembolso | Garantia de 30 dias | NovaLikes',
      description:
        'Leia a garantia de reembolso de 30 dias da NovaLikes, a elegibilidade, as exclusões, os cancelamentos, as reposições e o processo de solicitação.',
    },
    termsAndConditions: {
      title: 'Termos e condições | NovaLikes',
      description:
        'Leia os termos que regem os serviços da NovaLikes, pedidos, pagamentos, ferramentas gratuitas, responsabilidades do cliente, reembolsos e o uso do site.',
    },
    cookiePolicy: {
      title: 'Política de cookies | NovaLikes',
      description:
        'Saiba como a NovaLikes usa cookies e armazenamento do navegador para o carrinho, sessões de administração, preferências e outros recursos do site.',
    },
    disclaimer: {
      title: 'Aviso legal | NovaLikes',
      description:
        'Leia limitações importantes sobre os serviços da NovaLikes, plataformas de terceiros, ferramentas gratuitas, métricas de redes sociais e conteúdo baixado.',
    },
  },
  ar: {
    privacyPolicy: {
      title: 'سياسة الخصوصية | NovaLikes',
      description:
        'تعرّف كيف تجمع NovaLikes المعلومات وتستخدمها وتخزّنها وتعالجها عند استخدام الموقع والخدمات المدفوعة والأدوات المجانية والدعم.',
    },
    refundPolicy: {
      title: 'سياسة الاسترداد | ضمان 30 يومًا | NovaLikes',
      description:
        'اقرأ ضمان استرداد الأموال خلال 30 يومًا من NovaLikes، ومعايير الأهلية والاستثناءات والإلغاءات وإعادة التعبئة وعملية الطلب.',
    },
    termsAndConditions: {
      title: 'الشروط والأحكام | NovaLikes',
      description:
        'اقرأ الشروط التي تحكم خدمات NovaLikes والطلبات والمدفوعات والأدوات المجانية ومسؤوليات العميل والاسترداد واستخدام الموقع.',
    },
    cookiePolicy: {
      title: 'سياسة ملفات الارتباط | NovaLikes',
      description:
        'تعرّف كيف تستخدم NovaLikes ملفات الارتباط وتخزين المتصفح لسلة التسوق وجلسات الإدارة والتفضيلات وميزات أخرى في الموقع.',
    },
    disclaimer: {
      title: 'إخلاء المسؤولية | NovaLikes',
      description:
        'اقرأ قيودًا مهمة حول خدمات NovaLikes والمنصات الخارجية والأدوات المجانية ومقاييس وسائل التواصل والمحتوى الذي يتم تنزيله.',
    },
  },
};

for (const locale of LOCALIZED_LOCALES) {
  const uiPath = path.join(process.cwd(), 'content', 'locales', locale, 'ui.json');
  const ui = JSON.parse(readFileSync(uiPath, 'utf8')) as Record<string, unknown>;
  Object.assign(ui, extras[locale]);
  writeFileSync(uiPath, `${JSON.stringify(ui, null, 2)}\n`, 'utf8');

  const metaPath = path.join(process.cwd(), 'content', 'locales', locale, 'metadata.json');
  const meta = JSON.parse(readFileSync(metaPath, 'utf8')) as Record<string, unknown>;
  Object.assign(meta, legalMeta[locale]);
  writeFileSync(metaPath, `${JSON.stringify(meta, null, 2)}\n`, 'utf8');
}

console.log('Merged cart/checkout/legal chrome and legal metadata for', LOCALIZED_LOCALES.join(', '));
